### PR TITLE
Add JetBrains Toolbox

### LINKED ISSUE #10: Add JetBrains Toolbox
https://www.jetbrains.com/toolbox/app/

### PR DESCRIPTION
**Pull request by MartinX3**
Closed https://github.com/JonasGroeger/jetbrains-ppa/issues/10

Add JetBrains Toolbox

Add jetbrains-ppa.iml to the .gitignore file
(IntelliJ file)

Add packages/*.buildinfo to the .gitignore file

Remove package after failed download.

Integrated a workaround, occuring, because the JetBrains-Toolbox-App versioning is a little bit different

Give the user a hint, that he need to remove the IDEs by hand, if he removes the toolbox.

---
This change is [Reviewable](https://reviewable.io/reviews/jonasgroeger/jetbrains-ppa/14)

### CODE REVIEW

**Comment by MartinX3** [comment]
Only the person, who merge a PR is allwed to "sqash" them into one single commit.

I will only work with branches not and make a PR on my own master branch, to "sqash" the commits I made in a branch.

**Comment by JonasGroeger** [comment]
You can do
`git rebase -i ...` and then a force push to your master. Then create a PR.

**Comment by JonasGroeger** [comment]
I'm not sure I like the Toolbox in here. If more people want it we can add it but as of now I don't think its a good idea. People can install the IDE they want using the PPA.

**Comment by MartinX3** [comment]
Now I am a bit of angry, because **YOU** told me to make a fucking PR.
https://github.com/JonasGroeger/jetbrains-ppa/issues/10
`"I personally dont use the toolbox so feel free to make a PR."`

I invested my time to help **you** and this projekt.
I don't want to contribute to this project anymore.

**Pull request closed without merging**
