### PR TITLE
Added Android Studio versions

### PR DESCRIPTION
**Pull request by Zpecter**
Added all versions (branches) for Android Studio,.

### CODE REVIEW

**Comment by JonasGroeger** [comment]
Whats with the gvt URLs?

**Comment by Zpecter** [comment]
> Whats with the gvt URLs: `https://redirector.gvt1.com/`

Those are the links that Google provide, I guess they are like CDNs.

**Comment by JonasGroeger** [comment]
There is an issue in the `preinstall` script. It contains a version that does not follow the `x.y.z` schema but rather `x.y.z.q`. The Bash function [`update_package_version` in `update_packages`](https://github.com/JonasGroeger/jetbrains-ppa/blob/master/update-packages#L3) will only update the `x.y.z` part but keep the `q` part in place.

I'd recommend putting the full version into the `package.json` file so that [updating it](https://github.com/JonasGroeger/jetbrains-ppa/blob/master/update-packages#L72) works flawlessly.

**Comment by Zpecter** [comment]
I have updated the versions and also the packages.json

**Comment by JonasGroeger** [comment]
LGTM

**Comment by Zpecter** [comment]
Hi, I didn't know that. The problem is that Android Studio, although is based on IntelliJ IDEA, it is not maintained by JetBrains, but by Google, so I don't know how to get that information other than this site:

[https://developer.android.com/studio/archive](https://developer.android.com/studio/archive)

**Comment by Zpecter** [comment]
Hi, I'm creating an API to parse the above url and return a json similar to the one offered by JetBrains.

**Comment by JonasGroeger** [comment]
It's the only way. Check out update-packages in L55. There is where it would fail.

We need to have an API that provides us with the latest version. Is there something like this? I'd rather not scrape the website.

**Comment by Zpecter** [comment]
Yes, I think there should be an API too, I even sniffed the connection but it's encrypted and I only see that is something like this: https://dl.google.com, but I can't find the rest, that's the reason I created my own API by parsing the html from that url.

**Comment by JonasGroeger** [comment]
I used mitmproxy to intercept the HTTPS calls and found out that they use
```
https://dl.google.com/android/studio/patches/updates.xml
```
for the update check.

**Comment by Zpecter** [comment]
Hi, here is my API published:

[http://asdataparser.azurewebsites.net/products?code=AS&latest=true&type=release](http://asdataparser.azurewebsites.net/products?code=AS&latest=true&type=release)

**Comment by isaranghi** [comment]
Is there any update on this? I don't see Android Studio in the repo... I recently moved from Fedora to Debian and came across this repo.... but I was hoping that it would also have Android Studio... here is the Fedora COPR repo that support Android Studio.... is it possible to add similar way to fetch the version for android studio? -> (https://github.com/M3DZIK/rpm/tree/main/android-studio)

**Pull request merged**
